select * from sneaker_sales.customers;
select * from sneaker_sales.products;
select * from sneaker_sales.sales;
select * from sneaker_sales.sales_reprentative;
select * from sneaker_sales.suppliers;


# Objective (1) : "Analyzing Sales Performance" :

# (1).What is the total sales amount generated by each sales representative?
select SalesRepID , sum(TotalAmount) as 'Total_sales'
	from sneaker_sales.sales
	  group by SalesRepID 
        order by Total_sales;

# (2).How many products have been sold in each store location?
select ProductID ,StoreLocation ,sum(TotalAmount) as 'products_sold'
  from sneaker_sales.sales
    group by StoreLocation,ProductID
      order by  products_sold desc;

# (3).Which product category has the highest total sales amount?
select  t2.Category,sum(t1.TotalAmount) as 'Total_sales_Amount'
  from sneaker_sales.sales t1
   inner join sneaker_sales.products t2 on t1.ProductID = t2.ProductID
     group by t2.Category
       order by Total_sales_Amount  desc
         limit 1;
# chat gpt
SELECT p.Category, SUM(s.TotalAmount) AS 'TotalSalesAmount'
  FROM sneaker_sales.sales s
   JOIN sneaker_sales.products p ON s.ProductID = p.ProductID
     GROUP BY p.Category
       ORDER BY TotalSalesAmount DESC
		 LIMIT 1;


# (4).What is the average quantity of products sold per sale?
select SalesRepID, avg(Quantity) as 'Average'
  from sneaker_sales.sales
    group by SalesRepID
      order by Average desc;

# (5).Which customer has made the highest number of purchases?
select  t2.FirstName ,t2.LastName,sum(t1.SaleID) as 'Purchases' 
  from sneaker_sales.sales t1 
    inner join sneaker_sales.customers t2 on t1.CustomerID = t2.CustomerID
      group by t2.FirstName ,t2.LastName
        order by Purchases desc;

# (5.1).Which customer has made the highest total purchase amount?
select  t2.FirstName ,t2.LastName,sum(t1.TotalAmount) as 'Purchases' 
  from sneaker_sales.sales t1 
    inner join sneaker_sales.customers t2 on t1.CustomerID = t2.CustomerID
      group by t2.FirstName ,t2.LastName
        order by Purchases desc;

# (6).What is the distribution of total sales amounts across different months or days?
select  Date,sum(TotalAmount) as 'Total_sales'
   from sneaker_sales.sales
     group by Date
       order by  Total_sales desc;

# (7).How does the sales performance of different regions compare?
select  t2.Region, sum(t1.TotalAmount) as 'Total_sales'  
   from sneaker_sales.sales t1 
     inner join sneaker_sales.sales_reprentative t2 on t1.SalesRepID = t2.SalesRepID
       group by t2.Region
         order by Total_sales desc;


# (8).What is the total sales amount generated for each product?
select  t2.ProductName,sum(t1.TotalAmount) as 'Total_sales'
   from sneaker_sales.sales t1
     inner join sneaker_sales.products t2 on t1.ProductID = t2.ProductID
      group by t2.ProductName
         order by Total_sales desc;


# (9).What is the average sales amount per transaction  by name?
select  t2.FirstName ,t2.LastName, round(avg(TotalAmount))  as 'Average_sales'
  from sneaker_sales.sales  t1 
     inner join sneaker_sales.sales_reprentative t2 on t1.SalesRepID = t2.SalesRepID
        group by t2.FirstName ,t2.LastName
           order by Average_sales desc;


# (10).How many sales transactions were made by each sales representative?
select CustomerID as 'Sales_Transactions', SalesRepID
  from sneaker_sales.sales 
   group by Sales_Transactions,SalesRepID
    order by SalesRepID desc ;
    
